# Generated by Django 2.0.5 on 2019-02-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testwine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('region1', models.CharField(max_length=30)),
            ],
        ),
    ]
