# Generated by Django 2.0.5 on 2019-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='winedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('points', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('province', models.CharField(max_length=300)),
                ('region_1', models.CharField(max_length=300)),
                ('region_2', models.CharField(max_length=300)),
                ('variety', models.CharField(max_length=300)),
                ('winery', models.CharField(max_length=300)),
            ],
        ),
    ]
