# Generated by Django 2.0.5 on 2019-02-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_winedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winedata',
            name='country',
            field=models.CharField(default='not-available', max_length=30),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='description',
            field=models.CharField(default='not-available', max_length=300),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='designation',
            field=models.CharField(default='not-available', max_length=300),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='province',
            field=models.CharField(default='not-available', max_length=300),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='region_1',
            field=models.CharField(default='not-available', max_length=300),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='region_2',
            field=models.CharField(default='not-available', max_length=300),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='variety',
            field=models.CharField(default='not-available', max_length=300),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='winery',
            field=models.CharField(default='not-available', max_length=300),
        ),
    ]
