# Generated by Django 2.0.5 on 2019-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20190217_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winedata',
            name='description',
            field=models.CharField(default='not-available', max_length=3000),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='designation',
            field=models.CharField(default='not-available', max_length=3000),
        ),
    ]
