# Generated by Django 2.0.5 on 2019-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_auto_20190217_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winedata',
            name='points',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
